# Generated by Django 3.2 on 2022-04-13 14:59

import br.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('br', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='score',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='author',
            name='born',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), br.models.max_value_current_year]),
        ),
        migrations.AddField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('first_name', 'patronymic', 'last_name', 'born')},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'year')},
        ),
    ]
