# Generated by Django 3.2.6 on 2022-04-20 15:42

import book_review.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('born', models.DateField(help_text='YYYY-MM-DD', validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
            ],
            options={
                'ordering': ['first_name'],
                'unique_together': {('first_name', 'patronymic', 'last_name', 'born')},
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('original_title', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pub_date', models.DateField(help_text='YYYY-MM-DD')),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('full_img', models.ImageField(default='img/book_img/full/default-book-full.jpg', upload_to='img/book_img/full/')),
                ('small_img', models.ImageField(default='img/book_img/small/default-book-small.jpg', upload_to='img/book_img/small/')),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=80)),
                ('authors', models.ManyToManyField(to='book_review.Author')),
                ('genres', models.ManyToManyField(to='book_review.Genre')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('title', 'pub_date')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', models.TextField(max_length=8192)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_review.book')),
                ('owner', models.ForeignKey(on_delete=models.SET(book_review.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('book', 'owner')},
            },
        ),
    ]
