# Generated by Django 3.2.5 on 2021-07-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0003_auto_20210721_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='score',
            new_name='rating',
        ),
    ]
