# Generated by Django 3.2.5 on 2021-07-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0005_auto_20210721_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pub_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
