# Generated by Django 3.2.5 on 2021-07-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0008_alter_review_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50)),
        ),
    ]
