# Generated by Django 3.2.5 on 2021-07-22 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0014_alter_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genres',
        ),
    ]
