# Generated by Django 3.2.5 on 2021-07-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0018_alter_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reviewed_by',
        ),
    ]
