# Generated by Django 3.2.5 on 2021-07-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0020_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='plural_name',
            field=models.CharField(default='something', max_length=50),
        ),
    ]
