# Generated by Django 3.2.5 on 2021-07-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0021_genre_plural_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='plural_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
