# Generated by Django 3.2.5 on 2021-07-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0023_auto_20210727_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='BADSLUG', max_length=80),
        ),
    ]
