# Generated by Django 3.2.5 on 2021-07-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0025_alter_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=80),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
