# Generated by Django 3.2.5 on 2021-07-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0027_auto_20210727_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=80),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
