# Generated by Django 3.2.5 on 2021-07-29 21:12

import book_review.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_review', '0029_auto_20210728_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born',
            field=models.DateField(help_text='YYYY-MM-DD', validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(book_review.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
