# Generated by Django 3.2.5 on 2021-08-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0031_book_test1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='test1',
            new_name='img',
        ),
    ]
