# Generated by Django 3.2.5 on 2021-08-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0032_rename_test1_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(default='img/book_img/default_book.png', upload_to='img/book_img/'),
        ),
    ]
