# Generated by Django 3.2.5 on 2021-08-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0034_alter_book_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='img',
        ),
    ]
