# Generated by Django 3.2.5 on 2021-08-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0035_remove_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='full_img',
            field=models.ImageField(default='img/book_img/full/default-book-full.jpg', upload_to='img/book_img/full/'),
        ),
        migrations.AddField(
            model_name='book',
            name='short_img',
            field=models.ImageField(default='img/book_img/small/default_book-small.jpg', upload_to='img/book_img/small/'),
        ),
    ]
