# Generated by Django 3.2.5 on 2021-08-03 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0038_alter_book_small_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='small_img',
        ),
    ]
