# Generated by Django 3.2.5 on 2021-08-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0039_remove_book_small_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='small_img',
            field=models.ImageField(default='img/book_img/small/default-book-small.jpg', upload_to='img/book_img/small/'),
        ),
    ]
