# Generated by Django 3.2.5 on 2021-08-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0045_alter_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='original_title',
            field=models.CharField(max_length=80),
        ),
    ]
