# Generated by Django 3.2.6 on 2021-09-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0047_alter_review_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='original_title',
            field=models.CharField(blank=True, help_text="If it's different", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='In English', max_length=100),
        ),
    ]
