# Generated by Django 3.2.6 on 2021-09-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0048_auto_20210903_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='original_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
