# Generated by Django 3.2.6 on 2021-09-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0049_auto_20210903_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
