# Generated by Django 3.2.6 on 2021-09-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0050_remove_book_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
